servers:
  - name: backendV1
    host: localhost
    port: 9000
    urlMapping: /backend/v1
    protocol: http
  - name: stoppedBackend
    host: localhost
    port: 9001
    urlMapping: /backend/stopped
    protocol: http
redis:
  host: localhost
  port: 6379
  secondsToExpireCache: 30